### ISSUE TITLE
Idling Resources issue: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [ComposeIdlingResource] to become idle timed out

### ISSUE THREAD

**Issue by RivuChk** [RivuChk/Jetpack-Compose-MVI-Demo#1] opened 2020-06-21 15:04 UTC
UI Tests, interacting with `CircularProgressIndicator` and `AdapterList` are failing with `androidx.test.espresso.IdlingResourceTimeoutException: Wait for [ComposeIdlingResource] to become idle timed out`
The tests failing are marked with `@Ignore` for the time being, can be found at [app/src/androidTest/java/dev/rivu/mvijetpackcomposedemo/MovieAppUITests.kt](https://github.com/RivuChk/Jetpack-Compose-MVI-Demo/blob/master/app/src/androidTest/java/dev/rivu/mvijetpackcomposedemo/MovieAppUITests.kt)
Stacktrace:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [ComposeIdlingResource] to become idle timed out
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:342)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:361)
	at androidx.ui.test.android.SynchronizedTreeCollector.waitForIdle$ui_test_release(SynchronizedTreeCollector.kt:70)
	at androidx.ui.test.android.SynchronizedTreeCollector.collectAllSemanticsNodes$ui_test_release(SynchronizedTreeCollector.kt:51)
	at androidx.ui.test.FindersKt.getAllSemanticsNodes(Finders.kt:94)
	at androidx.ui.test.SemanticsNodeInteraction.fetchSemanticsNodes$ui_test_release(SemanticsNodeInteraction.kt:53)
	at androidx.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:116)
	at androidx.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:72)
	at androidx.ui.test.AssertionsKt.checkIsDisplayed(Assertions.kt:295)
	at androidx.ui.test.AssertionsKt.assertIsDisplayed(Assertions.kt:64)
	at dev.rivu.mvijetpackcomposedemo.MovieAppUITests.test_list_state(MovieAppUITests.kt:97)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at androidx.ui.test.android.AndroidComposeTestRule$AndroidComposeStatement.evaluate(AndroidComposeTestRule.kt:167)
	at androidx.ui.test.AnimationClockTestRule$AnimationClockStatement.evaluate(TestAnimationClock.kt:130)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2206)
Caused by: java.util.concurrent.ExecutionException: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [ComposeIdlingResource] to become idle timed out
	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:334)
	... 42 more
Caused by: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [ComposeIdlingResource] to become idle timed out
	at androidx.test.espresso.IdlingPolicy.handleTimeout(IdlingPolicy.java:61)
	at androidx.test.espresso.base.UiControllerImpl$5.resourcesHaveTimedOut(UiControllerImpl.java:434)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeout(IdlingResourceRegistry.java:481)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:414)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:525)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:447)
	at androidx.test.espresso.Espresso$1.run(Espresso.java:324)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)

```
While it's waiting for the idling resources, you can see in the attached screenshot, the expected UI is already showing in the emulator.
<img width="1680" alt="Screenshot 2020-06-21 at 8 32 50 PM" src="https://user-images.githubusercontent.com/9866905/85228007-6f624e00-b3fe-11ea-9302-c6f6f7ef1b56.png">

**Comment by RivuChk** [comment] 2020-07-01 03:08
Issue persists with new `LazyColumnItems` as well.

**Comment by RivuChk** [comment] 2020-07-01 03:15
Tried calling `waitForIdle`, even though it's not needed, since Compose calls it internally whenever you call something like `findByTag` or `findBySubstring`. Used `Modifier.testTag` in the `CircularProgressIndicator` and tried that with `LazyColumnItems` as well, the same result. 
 suspected LiveData earlier, so I tried setting value, instead of postValue, but it got an error, saying something like 'can't set value from background thread', so I tried using `runOnUIThread`, and `FrameManager.framed` but got no luck there as well.
With FrameManager.framed getting Cannot invoke `setValue` on a background thread (I tried calling `setValue` as with `postValue` it was all the same)
With `runOnUiThread` The value gets posted, I can see the UI change in the emulator, but still getting IdlingResourceTimeoutException: Wait for [ComposeIdlingResource] to become idle timed out after a while.

**Comment by RivuChk** [comment] 2020-07-01 05:16
As I believe this might be a bug, created an issue here: https://issuetracker.google.com/issues/160259537, if you agree, please upvote

**Comment by JoseAlcerreca** [comment] 2020-07-06 14:21
Not a bug on the Compose side. Added some findings to https://issuetracker.google.com/issues/160259537 that should be enough to close this issue.

**Comment by RivuChk** [comment] 2020-07-06 14:33
Thanks, I've looked into the status update and trying those right now. Thanks for being so helpful and awesome, and also for the awesome work. I'll work on the things mentioned by you.

**Comment by RivuChk** [comment] 2020-07-06 14:35
I'll close this issue here, once I have a fix ready from my side though. when I first opened this issue I didn't think it was from Compose side.

**Closed as completed** 2020-07-06 15:21 UTC
Labels: bug, help wanted, good first issue

**Comment by RowickaM** [comment] 2021-09-14 10:59
@RivuChk could you present what was wrong?

**Comment by hosseinaminii** [comment] 2022-06-08 08:51
When I use BottomSheetScaffold this error occurs, any suggestions?

**Comment by RivuChk** [comment] 2022-09-17 05:45
The fix is here: https://github.com/RivuChk/Jetpack-Compose-MVI-Demo/commit/f367fcc20eb29d89bf31c116628e2cf50c01709b
The issue described here: https://issuetracker.google.com/issues/160259537?pli=1
